### ISSUE TITLE
楼主可以封装上传服务器吗

### ISSUE THREAD

**Issue by shapolang** [xuexiangjys/XLog#5]
就是封装成通用的sdk,暴露出上传的方法，不同项目上传到不同的服务器

**Comment by xuexiangjys** [comment]
上传服务器的话,我建议直接使用阿里云或者其他云上传就可以了,没必要再去额外封装.

**Comment by xuexiangjys** [comment]
阿里云的oss上传给你借鉴一下:
https://help.aliyun.com/document_detail/32043.html?spm=a2c4g.11186623.6.1128.25d94947twYZJR
